type LayerName='rain'|'wind'|'hum'|'chime'
class ProceduralAudioEngine{
  private context?:AudioContext;private master?:GainNode;private layers=new Map<LayerName,GainNode>();private initialized=false;private chimeTimer?:number
  private noiseBuffer(context:AudioContext){const length=context.sampleRate*3;const buffer=context.createBuffer(1,length,context.sampleRate);const data=buffer.getChannelData(0);let last=0;for(let i=0;i<length;i++){const white=Math.random()*2-1;last=last*.96+white*.04;data[i]=white*.55+last*.45}return buffer}
  private noiseLayer(context:AudioContext,filterType:BiquadFilterType,frequency:number,gain:number){const source=context.createBufferSource();source.buffer=this.noiseBuffer(context);source.loop=true;const filter=context.createBiquadFilter();filter.type=filterType;filter.frequency.value=frequency;const layer=context.createGain();layer.gain.value=gain;source.connect(filter).connect(layer).connect(this.master!);source.start();return layer}
  async start(){if(!this.context){this.context=new AudioContext();this.master=this.context.createGain();this.master.gain.value=.55;this.master.connect(this.context.destination);const context=this.context;this.layers.set('rain',this.noiseLayer(context,'highpass',2100,.22));this.layers.set('wind',this.noiseLayer(context,'lowpass',620,.16));const humGain=context.createGain();humGain.gain.value=.1;humGain.connect(this.master);[55,82.5,110].forEach((frequency,index)=>{const oscillator=context.createOscillator();const gain=context.createGain();oscillator.type=index?'sine':'triangle';oscillator.frequency.value=frequency;gain.gain.value=index? .16:.24;oscillator.connect(gain).connect(humGain);oscillator.start()});this.layers.set('hum',humGain);const chime=context.createGain();chime.gain.value=.18;chime.connect(this.master);this.layers.set('chime',chime);this.chimeTimer=window.setInterval(()=>this.playChime(),6500);this.initialized=true}await this.context.resume()}
  private playChime(){if(!this.context||!this.initialized)return;const context=this.context;const layer=this.layers.get('chime');if(!layer)return;const now=context.currentTime;[0,7,12].forEach((step,index)=>{const oscillator=context.createOscillator();const gain=context.createGain();oscillator.type='sine';oscillator.frequency.value=440*Math.pow(2,step/12);gain.gain.setValueAtTime(0,now+index*.11);gain.gain.linearRampToValueAtTime(.12,now+index*.11+.025);gain.gain.exponentialRampToValueAtTime(.001,now+index*.11+1.8);oscillator.connect(gain).connect(layer);oscillator.start(now+index*.11);oscillator.stop(now+index*.11+2)})}
  async pause(){await this.context?.suspend()}
  setMaster(value:number){if(this.master)this.master.gain.setTargetAtTime(value,this.context!.currentTime,.05)}
  setLayer(name:LayerName,value:number){const layer=this.layers.get(name);if(layer)layer.gain.setTargetAtTime(value,this.context!.currentTime,.05)}
}
export const proceduralAudio=new ProceduralAudioEngine()
